name: ECS Infrastructure & Code Delivery

on:
  workflow_dispatch:
    inputs:
      action_name:
        type: choice
        description: Choose Event
        options:
        - Provision Infrastructure
        - Code Delivery

      reason:
        type: choice
        description: Choose AWS Reason
        options:
        - us-east-1
        - ap-south-1

      image_tag:
        type: choice
        description: Choose Docker Image Tag
        options:
        - latest
        - v1
        - v2

      repository_name:
        description: 'App Name'
        required: false
        default: "aws_ecs_flask"

      app_count:
        description: 'Desired App Count'
        required: false
        default: "3"

      fargate_cpu:
        description: 'Farget CPU'
        required: false
        default: "1024"

      fargate_memory:
        description: 'Farget Memory'
        required: false
        default: "2048"

jobs:
  terraform:
    name: "Update ECS Service"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.reason }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.10

      - name: Terraform Init
        id: init
        run: |
          echo -e "repository_name = \"${REPOSITORY_NAME}\"\n" >> terraform.auto.tfvars
          echo -e "image_tag = \"${IMAGE_TAG}\"\n" >> terraform.auto.tfvars
          echo -e "region = \"${AWS_REGION}\"\n" >> terraform.auto.tfvars
          echo -e "app_count = \"${APP_COUNT}\"\n" >> terraform.auto.tfvars
          echo -e "fargate_cpu = \"${FARGET_CPU}\"\n" >> terraform.auto.tfvars
          echo -e "fargate_memory = \"${FARGET_MEMORY}\"\n" >> terraform.auto.tfvars
          terraform init
        env:
          REPOSITORY_NAME: ${{ github.event.inputs.repository_name }}
          IMAGE_TAG: ${{ github.event.inputs.image_tag }}
          AWS_REGION: ${{ github.event.inputs.reason }}
          APP_COUNT: ${{ github.event.inputs.app_count }}
          FARGET_CPU: ${{ github.event.inputs.fargate_cpu }}
          FARGET_MEMORY: ${{ github.event.inputs.fargate_memory }}

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan
      - name: Terraform Apply
        run: |
          if [ $ACTION_NAME == "Provision Infrastructure" ]
          then
          terraform apply -auto-approve -target=module.ecs_app
          else
          terraform apply -auto-approve
          fi
        env:
          ACTION_NAME: ${{ github.event.inputs.action_name }}
